package com.wangyin.ebl.domain;

/**
 * 数据库表
 * @author wylaihuiying
 *
 */
public enum TableTypeEnum {
	//用户基础信息表
	LICENSE_USER_LOGIN("LICENSE_USER_LOGIN","LOGIN_NAME"),
	LICENSE_USER_BASIC("LICENSE_USER_BASIC","USER_ID"),
	LICENSE_USER_SECURITY("LICENSE_USER_SECURITY","USER_ID"),
	LICENSE_USER_EXTERNAL_INFO("LICENSE_USER_EXTERNAL_INFO","USER_ID"),
	LICENSE_SHIP_ADDR("LICENSE_SHIP_ADDR","USER_ID"),
	LICENSE_DIGITAL_CERT("LICENSE_DIGITAL_CERT","USER_ID"),
	
	//营业执照相关表
	LICENSE_PROXY_APPOINTMENT("LICENSE_PROXY_APPOINTMENT","BIZ_ID"),
	LICENSE_BIZ_ORDER("LICENSE_BIZ_ORDER","BIZ_ID"),
	LICENSE_BIZ_PRDT("LICENSE_BIZ_PRDT","BIZ_ID"),
	LICENSE_BIZ_ITEM("LICENSE_BIZ_ITEM","BIZ_ID"),
	LICENSE_BUSINESS_LICENSE("LICENSE_BUSINESS_LICENES","ENT_NAME"),
	LICENSE_GOODS_SHIP("LICENSE_GOODS_SHIP","BIZ_ID"),
	LICENSE_FILE_SIGN("LICENSE_FILE_SIGN","BIZ_ID"),
	
	//订单相关表
	LICENSE_ORDER_INFO("LICENSE_ORDER_INFO","BIZ_ID"),
	LICENSE_ORDER_PAY("LICENSE_ORDER_PAY","ORDER_NO"),
	LICENSE_ORDER_PRODUCT("LICENSE_ORDER_PRODUCT","ORDER_NO"),
	LICENSE_ORDER_REFUND("LICENSE_ORDER_REFUND","ORDER_NO"),
	
	//企业基础信息表
	LICENSE_ENT_LOGIN("LICENSE_ENT_LOGIN","ENT_ID"),
	LICENSE_ENT_AUTH("LICENSE_ENT_AUTH","ENT_ID"),
	LICENSE_STORE("LICENSE_STORE","ENT_ID"),
	LICENSE_SERVICE_APPLY("TLICENSE_SERVICE_APPLY","TAX_NO"),
	
	
	//企业税务信息表
	LICENSE_TAX_SERVER_INFO("LICENSE_TAX_SERVER_INFO","TAX_NO"),
	LICENSE_TAX_INFO("LICENSE_TAX_INFO","TAX_NO"),
	LICENSE_TAX_RATE_INFO("LICENSE_TAX_RATE_INFO","TAX_NO"),
	LICENSE_DZF_CONTRACT("LICENSE_DZF_CONTRACT","TAX_NO"),
	LICENSE_TAX_PAY("LICENSE_TAX_PAY","TAX_NO"),
	LICENSE_TAX_PAY_DETAIL("LICENSE_TAX_PAY_DETAIL","TAX_NO"),
	LICENSE_TAX_CREDENTIAL("LICENSE_TAX_CREDENTIAL","ENT_ID"),
	
	//企业电子发票信息
	LICENSE_INVOICE_INFO("LICENSE_INVOICE_INFO","ENT_ID"),
	LICENSE_INVOICE_APPLY_INFO("LICENSE_INVOICE_APPLY_INFO","INVOICE_APPLY_ID"),
	LICENSE_INVOICE_PLATFORM_ORDER("LICENSE_INVOICE_PLATFORM_ORDER","PF_ORDER_ID"),
	LICENSE_INVOICE_PLATFORM_ORDER_PRODUCT("LICENSE_INVOICE_PLATFORM_ORDER_PRODUCT","PF_ORDER_ID"),
	LICENSE_INVOICE_PRODUCT("LICENSE_INVOICE_PRODUCT","INVOICE_APPLY_ID"),
	LICENSE_INVOICE_TAX("LICENSE_INVOICE_TAX","INVOICE_APPLY_ID"),
	LICENSE_INVOICE_PRODUCT_ADRATE("LICENSE_INVOICE_PRODUCT_ADRATE","INVOICE_APPLY_ID");
	
	
	private String tableName;
	private String primaryKey;
	public String getTableName() {
		return tableName;
	}
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}
	public String getPrimaryKey() {
		return primaryKey;
	}
	public void setPrimaryKey(String primaryKey) {
		this.primaryKey = primaryKey;
	}
	private TableTypeEnum(String tableName, String primaryKey) {
		this.tableName = tableName;
		this.primaryKey = primaryKey;
	}
	
	
}